#!/usr/bin/env bash
set -euo pipefail

brew install --cask ghostty

cat > $HOME/Library/Application\ Support/com.mitchellh.ghostty/config.ghostty << EOF
# Config generated by Ghostty Config
# https://ghostty.zerebos.com

clipboard-read = allow
cursor-style-blink = false
fullscreen = false
shell-integration = zsh
theme = TokyoNight Night
window-show-tab-bar = always

# Hide emoji from tab title
macos-titlebar-proxy-icon = hidden
shell-integration-features = no-title

EOF
